---
title: "R Notebook"
output: html_notebook
---

```{r}
con <- dbConnect(Postgres(), "postgres", "localhost", 1111, "pgpass", "postgres")

dbExecute(con, "CREATE SCHEMA identifier_test")

df <- data.frame(
  numbers = 1:10,
  letters  = letters[1:10],
  LETTERS = LETTERS[1:10]
)

dbWriteTable(con,
             dbQuoteIdentifier(con, DBI::Id(c(schema = "identifier_test", table = "a_table"))),
             df)


dbGetQuery(con,
           sprintf("SELECT * FROM %s", dbQuoteIdentifier(con, DBI::Id(c(schema = "identifier_test", table = "a_table")))))

# Seems safe
dbQuoteIdentifier(con, DBI::Id(c(schema = "\"Robert');DROP TABLE students;---", table = "a_table")))
```

And now for the main attraction: Can this be used in a prepared query?
Because if so, we can save ourselfes the query_ functions and make code more readable
```{r}
dbGetQuery(con, 
           "SELECT * FROM $1
           WHERE numbers > $2",
           list(
             dbQuoteIdentifier(con, DBI::Id(c(schema = "identifier_test", table = "a_table"))),
             4
           ))
```

Nüpe, apparently not (in the way I imagined...)
