---
title: "md field performance w/o branch"
output: html_notebook
---
```{r setup}
tsl <- lapply(1:10000, function(x){ts(x, start = 2020, end = 2023, frequency = 4)})
names(tsl) <- sprintf("ts%s", seq_along(tsl))
md <- list(
  field1 = 1,
  field2 = 2,
  field3 = "some text value",
  field4 = "have some more"
)
stuff <- data.frame(
  ts_key = names(tsl),
  locale = "de",
  meta_data = as.character(jsonlite::toJSON(md), auto_unbox = TRUE)
)

md2 <- md
md2$field5 <- 5
stuff2 <- data.frame(
  ts_key = names(tsl),
  locale = "de",
  meta_data = as.character(jsonlite::toJSON(md2), auto_unbox = TRUE)
)
```
```{r}
con <- connect_to_test_db()
dbWriteTable(con,
             "md_to_insert",
             stuff,
             field.types = c(
               ts_key = "text",
               locale = "text",
               meta_data = "jsonb"
             ),
             overwrite = TRUE)

dbWriteTable(con,
             "md_with_add",
             stuff2,
             field.types = c(
               ts_key = "text",
               locale = "text",
               meta_data = "jsonb"),
             overwrite = TRUE)

dbExecute(con, "DROP TABLE IF EXISTS md_after")
dbExecute(con, "CREATE TABLE IF NOT EXISTS md_after(
          ts_key TEXT,
          locale TEXT,
          meta_data JSONB,
          PRIMARY KEY (ts_key, locale))")
microbenchmark::microbenchmark(old = {
  dbExecute(con, "UPDATE md_after
                  SET meta_data = md_to_insert.meta_data,
                  locale = md_to_insert.locale
                  FROM md_to_insert
                  WHERE md_to_insert.ts_key = md_after.ts_key
                  AND md_to_insert.locale = md_after.locale;")
  dbExecute(con, "
                  
                  ---
                  INSERT INTO md_after
                  SELECT md_to_insert.ts_key,
                  md_to_insert.locale,
                  md_to_insert.meta_data
                  FROM md_to_insert
                  LEFT OUTER JOIN md_after
                  ON md_after.ts_key = md_to_insert.ts_key
                  AND md_after.locale = md_to_insert.locale
                  WHERE md_after.ts_key IS NULL 
                  AND md_after.locale IS NULL;")
},
new = {
  dbExecute(con, "INSERT INTO md_after
  SELECT *
  FROM md_to_insert
  ON CONFLICT (ts_key, locale) DO UPDATE
  SET
    meta_data = md_after.meta_data || EXCLUDED.meta_data;")
},
setup = {
  message("beep!")
  dbExecute(con, "DELETE FROM md_after")
  dbExecute(con, "INSERT INTO md_after (
            SELECT * FROM md_to_insert LIMIT 5000)")
},
times = 10)

# queries that add a field
microbenchmark::microbenchmark(old = {
  dbExecute(con, "UPDATE md_after
                  SET meta_data = md_with_add.meta_data,
                  locale = md_with_add.locale
                  FROM md_with_add
                  WHERE md_with_add.ts_key = md_after.ts_key
                  AND md_with_add.locale = md_after.locale;")
  dbExecute(con, "
                  
                  ---
                  INSERT INTO md_after
                  SELECT md_with_add.ts_key,
                  md_with_add.locale,
                  md_with_add.meta_data
                  FROM md_with_add
                  LEFT OUTER JOIN md_after
                  ON md_after.ts_key = md_with_add.ts_key
                  AND md_after.locale = md_with_add.locale
                  WHERE md_after.ts_key IS NULL 
                  AND md_after.locale IS NULL;")
},
new = {
  dbExecute(con, "INSERT INTO md_after
  SELECT *
  FROM md_with_add
  ON CONFLICT (ts_key, locale) DO UPDATE
  SET
    meta_data = md_after.meta_data || EXCLUDED.meta_data;")
},
setup = {
  message("beep!")
  dbExecute(con, "DELETE FROM md_after")
  dbExecute(con, "INSERT INTO md_after (
            SELECT * FROM md_to_insert LIMIT 5000)")
},
times = 10)

# queries that remove a field
microbenchmark::microbenchmark(old = {
  dbExecute(con, "UPDATE md_after
                  SET meta_data = md_to_insert.meta_data,
                  locale = md_to_insert.locale
                  FROM md_to_insert
                  WHERE md_to_insert.ts_key = md_after.ts_key
                  AND md_to_insert.locale = md_after.locale;")
  dbExecute(con, "
                  
                  ---
                  INSERT INTO md_after
                  SELECT md_to_insert.ts_key,
                  md_to_insert.locale,
                  md_to_insert.meta_data
                  FROM md_to_insert
                  LEFT OUTER JOIN md_after
                  ON md_after.ts_key = md_to_insert.ts_key
                  AND md_after.locale = md_to_insert.locale
                  WHERE md_after.ts_key IS NULL 
                  AND md_after.locale IS NULL;")
},
new = {
  dbExecute(con, "INSERT INTO md_after
  SELECT *
  FROM md_to_insert
  ON CONFLICT (ts_key, locale) DO UPDATE
  SET
    meta_data = md_after.meta_data || EXCLUDED.meta_data;")
},
setup = {
  message("beep!")
  dbExecute(con, "DELETE FROM md_after")
  dbExecute(con, "INSERT INTO md_after (
            SELECT * FROM md_with_add LIMIT 5000)")
},
times = 10)
```
