---
title: "Grundlagenforschung on how to read ts_data"
output: html_notebook
---

```{r}
library(data.table)
library(RPostgres)
library(jsonlite)
library(xts)

con <- dbConnect(Postgres(), "postgres", "localhost", 1111, "pgpass", "postgres")
dbExecute(con, "DELETE FROM timeseries.timeseries_main")
dbExecute(con, "DELETE FROM timeseries.releases")

tsl <- tstools::generate_random_ts(5000, lengths = 200)
class(tsl) <- c("tslist", "list")
t0 <- Sys.time()
store_time_series(con, tsl, "lotsaseries", "public", valid_from = "2019-01-01")
difftime(Sys.time(), t0, units = "secs")
```

```{r}
n_to_read <- 1000

keys_to_read <- paste0("('", paste(sample(names(tsl), n_to_read), collapse = "','"), "')")

# To test jsonb: replace json_array_elements with jsonb_array_elements and create table with JSONB type
dt_way <- function(con) {
  dt <- data.table(dbGetQuery(con, 
                   sprintf("select
                            ts_key,
                            json_array_elements(ts_data->'time')#>>'{}' as time,
                            json_array_elements(ts_data->'value') as value,
                            ts_data->'frequency' as freq
                            from timeseries.timeseries_main
                            where ts_key in %s", keys_to_read)
                   ))
  
  
  tsl <- dt[, {
    if(is.null(freq[1])) {
      
    } else {
      .(ts_obj = list(ts(
        as.numeric(value),
        start = date_to_index(time[1]),
        frequency = as.numeric(freq[1])
      )))
    }
  }, by = ts_key]
  
  out <- tsl$ts_obj
  names(out) <- tsl[, ts_key]
  out
}

json_way <- function(con) {
  xx <- data.table(dbGetQuery(
    con,
    sprintf("SELECT ts_key, ts_data FROM timeseries.timeseries_main where ts_key in %s", keys_to_read)
  ))
  
  tsl <- xx[, {
      dta <- fromJSON(ts_data)
      if(is.null(dta$frequency)) {
        
      } else {
         .(ts_obj = list(ts(
           dta$value,
           start = date_to_index(dta$time[1]),
           frequency = as.numeric(dta$frequency[1])
         )))
      }
    }, by = ts_key]
  
  out <- tsl$ts_obj
  names(out) <- tsl$ts_key
  out
}

microbenchmark(
  dt_way(con),
  json_way(con),
  times = 3
)
```

With JSON column type, the json_way is a breezy ~20x times faster.
With JSONB, still ~3x faster, plus inserts take a slight performance hit.
-> let's go with the tsl way!