context("collections - insert")

con <- NULL
if(is_test_db_reachable()) {
  con <- connect_to_test_db()
}


# db_collection_add -------------------------------------------------------


# TODO: Tests for db_call_function args

test_with_fresh_db(con, "db_collection_add returns OK", {
  result <- db_collection_add(con,
                              "tests first",
                              "ts4")

  expect_is(result, "list")
  expect_named(result, c("status", "message"))
  expect_equal(result$status, "ok")
})

test_with_fresh_db(con, "db_collection_add warns if keys not in catalog", {
  expect_warning(db_collection_add(con,
                                   "tests first",
                                   "tsx"), "specific collection")
})

test_with_fresh_db(con, "db_collection_add returns warning keys not in catalog", {
  result <- suppressWarnings(db_collection_add(con,
                              "tests first",
                              "tsx"))

  expect_is(result, "list")
  expect_named(result, c("status", "message", "invalid_keys"))
  expect_equal(result$status, "warning")
  expect_equal(result$invalid_keys, "tsx")
})

test_with_fresh_db(con, "db_collection_add add keys to existing", {
  db_collection_add(con, "tests first", "vts1", user = "test")

  result <- dbGetQuery(con, "SELECT * FROM timeseries.collect_catalog
                             JOIN timeseries.collections
                             ON timeseries.collect_catalog.id = timeseries.collections.id
                             AND name = 'tests first'")

  expect_equal(nrow(result), 4)
  expect_setequal(result$ts_key, c("ts1", "ts2", "ts3", "vts1"))
})

test_with_fresh_db(con, "db_collection_add add new collection & keys", {
  db_collection_add(con,
                    "tests new",
                    c("vts1", "vts2"),
                    user = "test",
                    description = "a collection generated by a test")

  collections_result <- dbGetQuery(con, "SELECT * FROM timeseries.collections
                                         WHERE name = 'tests new'
                                         AND owner = 'test'")

  expect_equal(collections_result[, -1], data.frame(
    name = "tests new",
    owner = "test",
    description = "a collection generated by a test",
    stringsAsFactors = FALSE
  ))

  collect_catalog_result <- dbGetQuery(con, "SELECT timeseries.collections.id, ts_key FROM timeseries.collect_catalog
                                       JOIN timeseries.collections
                                       ON timeseries.collect_catalog.id = timeseries.collections.id
                                       AND name = 'tests new'")

  expect_equal(collect_catalog_result, data.frame(
    id = collections_result$id,
    ts_key = c("vts1", "vts2"),
    stringsAsFactors = FALSE
  ))
})


# db_collect_remove -------------------------------------------------------

test_with_fresh_db(con, "db_collection_remove removing some keys returns ok", {
  result <- db_collection_remove(con,
                                 collection_name = "tests first",
                                 keys = "ts1",
                                 user = "test")
  expect_is(result, "list")
  expect_named(result, c("status", "message"))
  expect_equal(result$status, "ok")
})

test_with_fresh_db(con, "db_collection_remove warns if combo not found", {
  expect_error(db_collection_remove(con,
                                      collection_name = "not a collection",
                                      keys = c("does", "it", "matter?"),
                                      user = "alexandra_maine"), "not exist")
})

test_with_fresh_db(con, "db_collection_remove also removing collection", {
  result <- db_collection_remove(con,
                                 collection_name = "tests second",
                                 keys = c("ts4", "ts5"),
                                 user = "test")

  expect_is(result, "list")
  expect_named(result, c("status", "message", "removed_collection"))
  expect_equal(result$status, "notice")
})

test_with_fresh_db(con, "db_collection_remove state", {
  db_collection_remove(con,
                       collection_name = "tests first",
                       keys = c("ts1"),
                       user = "test")

  result <- dbGetQuery(con, "SELECT ts_key FROM timeseries.collect_catalog
                             JOIN timeseries.collections
                             ON timeseries.collect_catalog.id = timeseries.collections.id
                             AND name = 'tests first'")

  expect_setequal(result$ts_key, c("ts2", "ts3"))

  result_collections <- dbGetQuery(con, "SELECT 1 FROM timeseries.collections
                                         WHERE name = 'tests first'")

  expect_equal(nrow(result_collections), 1)
})

test_with_fresh_db(con, "db_collection_remove with remove collection state", {
  db_collection_remove(con,
                       collection_name = "tests first",
                       keys = c("ts1", "ts2", "ts3"),
                       user = "test")

  result <- dbGetQuery(con, "SELECT ts_key FROM timeseries.collect_catalog
                       JOIN timeseries.collections
                       ON timeseries.collect_catalog.id = timeseries.collections.id
                       AND name = 'tests first'")

  expect_equal(nrow(result), 0)

  result_collections <- dbGetQuery(con, "SELECT 1 FROM timeseries.collections
                                   WHERE name = 'tests first'")

  expect_equal(nrow(result_collections), 0)
})


# db_collection_delete ----------------------------------------------------

test_with_fresh_db(con, "db_collection_delete returns ok", {
  # In case anyone in the future should care: I wrote this with my eyes closed. o.Ô
  result <- db_collection_delete(con,
                                 collection_name = "tests first",
                                 user = "test")

  expect_is(result, "list")
  expect_named(result, c("status", "message", "id"))
  expect_equal(result$status, "ok")
})

test_with_fresh_db(con, "db_collection_delete warns if collection+user not found", {
  expect_warning(db_collection_delete(con,
                                      collection_name = "rubber duckie",
                                      user = "The other Severin"), "not be found")
})

test_with_fresh_db(con, "db_collection_delete warning contents", {
  result <- suppressWarnings(db_collection_delete(con,
                                                  collection_name = "rubber duckie",
                                                  user = "The other Severin"))

  expect_is(result, "list")
  expect_named(result, c("status", "message"))
  expect_equal(result$status, "warning")
})

test_with_fresh_db(con, "db_collection_delete db state", {
  out <- db_collection_delete(con,
                       collection_name = "tests first",
                       user = "test")

  result_collections <- dbGetQuery(con, "SELECT * FROM timeseries.collections
                                         WHERE name = 'tests first'")
  expect_equal(nrow(result_collections), 0)

  result_collect_catalog <- dbGetQuery(con, sprintf("SELECT * FROM timeseries.collect_catalog WHERE id = '%s'", out$id))

  expect_equal(nrow(result_collect_catalog), 0)
})

test_with_fresh_db(con, "db_collection_delete with missing user+collection does nothing", {
  db_collection_delete(con,
                       collection_name = "xxx",
                       user = "whoever")

  result_collections <- dbGetQuery(con, "SELECT * FROM timeseries.collections")
  expect_equal(nrow(result_collections), 3)

  result_collect_catalog <- dbGetQuery(con, "SELECT * FROM timeseries.collect_catalog")
  expect_equal(nrow(result_collect_catalog), 8)
})
