context("collections - insert")

if(is_test_db_reachable()) {
  con_admin <- connect_to_test_db()
  con_writer <- connect_to_test_db("dev_writer")
  con_reader <- connect_to_test_db("dev_reader_public")
}


# db_collection_add -------------------------------------------------------


# TODO: Tests for db_call_function args

test_with_fresh_db(con_admin, "db_collection_add returns OK", {
  result <- db_collection_add(con_writer,
                              "tests first",
                              "ts4",
                              schema = "tsdb_test")

  expect_is(result, "list")
  expect_named(result, c("status", "message"))
  expect_equal(result$status, "ok")
})

test_with_fresh_db(con_admin, "db_collection_add warns if keys not in catalog", {
  expect_warning(db_collection_add(con_writer,
                                   "tests first",
                                   "tsx",
                                   schema = "tsdb_test"), "specific collection")
})

test_with_fresh_db(con_admin, "db_collection_add returns warning keys not in catalog", {
  result <- suppressWarnings(db_collection_add(con_writer,
                                               "tests first",
                                               "tsx",
                                               schema = "tsdb_test"))

  expect_is(result, "list")
  expect_named(result, c("status", "message", "invalid_keys"))
  expect_equal(result$status, "warning")
  expect_equal(result$invalid_keys, "tsx")
})

test_with_fresh_db(con_admin, "db_collection_add add keys to existing", {
  db_collection_add(con_writer, "tests first", "vts1", user = "test",
                    schema = "tsdb_test")

  result <- dbGetQuery(con_admin, "SELECT * FROM tsdb_test.collect_catalog
                             JOIN tsdb_test.collections
                             ON tsdb_test.collect_catalog.id = tsdb_test.collections.id
                             AND name = 'tests first'")

  expect_equal(nrow(result), 4)
  expect_setequal(result$ts_key, c("ts1", "ts2", "ts3", "vts1"))
})

test_with_fresh_db(con_admin, "db_collection_add add new collection & keys", {
  db_collection_add(con_writer,
                    "tests new",
                    c("vts1", "vts2"),
                    user = "test",
                    description = "a collection generated by a test",
                    schema = "tsdb_test")

  collections_result <- dbGetQuery(con_admin, "SELECT * FROM tsdb_test.collections
                                         WHERE name = 'tests new'
                                         AND owner = 'test'")

  expect_equal(collections_result[, -1], data.frame(
    name = "tests new",
    owner = "test",
    description = "a collection generated by a test",
    stringsAsFactors = FALSE
  ))

  collect_catalog_result <- dbGetQuery(con_admin, "SELECT tsdb_test.collections.id, ts_key FROM tsdb_test.collect_catalog
                                       JOIN tsdb_test.collections
                                       ON tsdb_test.collect_catalog.id = tsdb_test.collections.id
                                       AND name = 'tests new'
                                       ORDER BY ts_key")

  expect_equal(collect_catalog_result, data.frame(
    id = collections_result$id,
    ts_key = c("vts1", "vts2"),
    stringsAsFactors = FALSE
  ))
})

test_with_fresh_db(con_admin, "reader may create sets and add keys", {
  db_collection_add(con_reader,
                    "tests new",
                    c("vts1", "vts2"),
                    user = "test",
                    description = "a collection generated by a test",
                    schema = "tsdb_test")

  collections_result <- dbGetQuery(con_admin, "SELECT * FROM tsdb_test.collections
                                   WHERE name = 'tests new'
                                   AND owner = 'test'")

  expect_equal(collections_result[, -1], data.frame(
    name = "tests new",
    owner = "test",
    description = "a collection generated by a test",
    stringsAsFactors = FALSE
  ))

  collect_catalog_result <- dbGetQuery(con_admin, "SELECT tsdb_test.collections.id, ts_key FROM tsdb_test.collect_catalog
                                       JOIN tsdb_test.collections
                                       ON tsdb_test.collect_catalog.id = tsdb_test.collections.id
                                       AND name = 'tests new'
                                       ORDER BY ts_key")

  expect_equal(collect_catalog_result, data.frame(
    id = collections_result$id,
    ts_key = c("vts1", "vts2"),
    stringsAsFactors = FALSE
  ))
})

# db_collect_remove -------------------------------------------------------

context("collections - remove")

test_with_fresh_db(con_admin, "db_collection_remove removing some keys returns ok", {
  result <- db_collection_remove(con_writer,
                                 collection_name = "tests first",
                                 keys = "ts1",
                                 user = "test",
                                 schema = "tsdb_test")
  expect_is(result, "list")
  expect_named(result, c("status", "message"))
  expect_equal(result$status, "ok")
})

test_with_fresh_db(con_admin, "db_collection_remove warns if combo not found", {


  expect_error(db_collection_remove(con_writer,
                                    collection_name = "not a collection",
                                    keys = c("does", "it", "matter?"),
                                    user = "alexandra_maine",
                                    schema = "tsdb_test"), "not exist")
})

test_with_fresh_db(con_admin, "db_collection_remove also removing collection", {
  result <- db_collection_remove(con_writer,
                                 collection_name = "tests second",
                                 keys = c("ts4", "ts5"),
                                 user = "test",
                                 schema = "tsdb_test")

  expect_is(result, "list")
  expect_named(result, c("status", "message", "removed_collection"))
  expect_equal(result$status, "notice")
})

test_with_fresh_db(con_admin, "db_collection_remove state", {
  db_collection_remove(con_writer,
                       collection_name = "tests first",
                       keys = c("ts1"),
                       user = "test",
                       schema = "tsdb_test")

  result <- dbGetQuery(con_admin, "SELECT ts_key FROM tsdb_test.collect_catalog
                             JOIN tsdb_test.collections
                             ON tsdb_test.collect_catalog.id = tsdb_test.collections.id
                             AND name = 'tests first'")

  expect_setequal(result$ts_key, c("ts2", "ts3"))

  result_collections <- dbGetQuery(con_admin, "SELECT 1 FROM tsdb_test.collections
                                         WHERE name = 'tests first'")

  expect_equal(nrow(result_collections), 1)
})

test_with_fresh_db(con_admin, "db_collection_remove with remove collection state", {
  db_collection_remove(con_writer,
                       collection_name = "tests first",
                       keys = c("ts1", "ts2", "ts3"),
                       user = "test",
                       schema = "tsdb_test")

  result <- dbGetQuery(con_admin, "SELECT ts_key FROM tsdb_test.collect_catalog
                       JOIN tsdb_test.collections
                       ON tsdb_test.collect_catalog.id = tsdb_test.collections.id
                       AND name = 'tests first'")

  expect_equal(nrow(result), 0)

  result_collections <- dbGetQuery(con_admin, "SELECT 1 FROM tsdb_test.collections
                                   WHERE name = 'tests first'")

  expect_equal(nrow(result_collections), 0)
})

test_with_fresh_db(con_admin, "reader may remove from collections", {
  db_collection_remove(con_reader,
                       collection_name = "tests first",
                       keys = c("ts1"),
                       user = "test",
                       schema = "tsdb_test")

  result <- dbGetQuery(con_admin, "SELECT ts_key FROM tsdb_test.collect_catalog
                             JOIN tsdb_test.collections
                             ON tsdb_test.collect_catalog.id = tsdb_test.collections.id
                             AND name = 'tests first'")

  expect_setequal(result$ts_key, c("ts2", "ts3"))

  result_collections <- dbGetQuery(con_admin, "SELECT 1 FROM tsdb_test.collections
                                         WHERE name = 'tests first'")

  expect_equal(nrow(result_collections), 1)
})

# db_collection_delete ----------------------------------------------------
context("collections - delete")

test_with_fresh_db(con_admin, "db_collection_delete returns ok", {
  # In case anyone in the future should care: I wrote this with my eyes closed. o.Ô
  result <- db_collection_delete(con_writer,
                                 collection_name = "tests first",
                                 user = "test",
                                 schema = "tsdb_test")

  expect_is(result, "list")
  expect_named(result, c("status", "message", "id"))
  expect_equal(result$status, "ok")
})

test_with_fresh_db(con_admin, "db_collection_delete warns if collection+user not found", {
  expect_warning(db_collection_delete(con_writer,
                                      collection_name = "rubber duckie",
                                      user = "The other Severin",
                                      schema = "tsdb_test"), "not be found")
})

test_with_fresh_db(con_admin, "db_collection_delete warning contents", {
  result <- suppressWarnings(db_collection_delete(con_writer,
                                                  collection_name = "rubber duckie",
                                                  user = "The other Severin",
                                                  schema = "tsdb_test"))

  expect_is(result, "list")
  expect_named(result, c("status", "message"))
  expect_equal(result$status, "warning")
})

test_with_fresh_db(con_admin, "db_collection_delete db state", {
  out <- db_collection_delete(con_writer,
                              collection_name = "tests first",
                              user = "test",
                              schema = "tsdb_test")

  result_collections <- dbGetQuery(con_admin, "SELECT * FROM tsdb_test.collections
                                         WHERE name = 'tests first'")
  expect_equal(nrow(result_collections), 0)

  result_collect_catalog <- dbGetQuery(con_admin, sprintf("SELECT * FROM tsdb_test.collect_catalog WHERE id = '%s'", out$id))

  expect_equal(nrow(result_collect_catalog), 0)
})

test_with_fresh_db(con_admin, "db_collection_delete with missing user+collection does nothing", {
  suppressWarnings(db_collection_delete(con_writer,
                                        collection_name = "xxx",
                                        user = "whoever",
                                        schema = "tsdb_test"))

  result_collections <- dbGetQuery(con_admin, "SELECT * FROM tsdb_test.collections")
  expect_equal(nrow(result_collections), 3)

  result_collect_catalog <- dbGetQuery(con_admin, "SELECT * FROM tsdb_test.collect_catalog")
  expect_equal(nrow(result_collect_catalog), 8)
})

test_with_fresh_db(con_admin, "reader may delete collections", {
  out <- db_collection_delete(con_reader,
                              collection_name = "tests first",
                              user = "test",
                              schema = "tsdb_test")

  result_collections <- dbGetQuery(con_admin, "SELECT * FROM tsdb_test.collections
                                   WHERE name = 'tests first'")
  expect_equal(nrow(result_collections), 0)

  result_collect_catalog <- dbGetQuery(con_admin, sprintf("SELECT * FROM tsdb_test.collect_catalog WHERE id = '%s'", out$id))

  expect_equal(nrow(result_collect_catalog), 0)
})
