REVOKE EXECUTE ON FUNCTION timeseries.insert_collect_from_tmp FROM public;
REVOKE EXECUTE ON FUNCTION timeseries.collection_remove FROM public;
REVOKE EXECUTE ON FUNCTION timeseries.collection_delete FROM public;
REVOKE EXECUTE ON FUNCTION timeseries.dataset_exists FROM public;
REVOKE EXECUTE ON FUNCTION timeseries.keys_in_dataset FROM public;
REVOKE EXECUTE ON FUNCTION timeseries.get_set_of_keys FROM public;
REVOKE EXECUTE ON FUNCTION timeseries.read_metadata_raw FROM public;
REVOKE EXECUTE ON FUNCTION timeseries.read_metadata_localized_raw FROM public;
REVOKE EXECUTE ON FUNCTION timeseries.read_ts_raw(TEXT[], DATE, BOOLEAN) FROM public;
REVOKE EXECUTE ON FUNCTION timeseries.read_ts_raw(DATE, BOOLEAN) FROM public;
REVOKE EXECUTE ON FUNCTION timeseries.read_ts_dataset_raw(TEXT[], DATE, BOOLEAN) FROM public;
REVOKE EXECUTE ON FUNCTION timeseries.read_ts_dataset_raw(DATE, BOOLEAN) FROM public;
REVOKE EXECUTE ON FUNCTION timeseries.get_latest_vintages_metadata FROM public;
REVOKE EXECUTE ON FUNCTION timeseries.get_latest_vintages_metadata_localized FROM public;
REVOKE EXECUTE ON FUNCTION timeseries.fill_read_tmp_regex FROM public;
REVOKE EXECUTE ON FUNCTION timeseries.create_dataset FROM public;
REVOKE EXECUTE ON FUNCTION timeseries.assign_dataset FROM public;
REVOKE EXECUTE ON FUNCTION timeseries.md_unlocal_upsert FROM public;
REVOKE EXECUTE ON FUNCTION timeseries.md_local_upsert FROM public;
REVOKE EXECUTE ON FUNCTION timeseries.build_meta_status FROM public;
REVOKE EXECUTE ON FUNCTION timeseries.insert_from_tmp FROM public;
REVOKE EXECUTE ON FUNCTION timeseries.list_datasets FROM public;
REVOKE EXECUTE ON FUNCTION timeseries.change_access_level FROM public;
REVOKE EXECUTE ON FUNCTION timeseries.change_access_level_dataset FROM public;
REVOKE EXECUTE ON FUNCTION timeseries.dataset_delete FROM public;
REVOKE EXECUTE ON FUNCTION timeseries.delete_ts FROM public;
REVOKE EXECUTE ON FUNCTION timeseries.delete_ts_edge FROM public;
REVOKE EXECUTE ON FUNCTION timeseries.delete_ts_old_vintages FROM public;
REVOKE EXECUTE ON FUNCTION timeseries.dataset_trim FROM public;
REVOKE EXECUTE ON FUNCTION timeseries.prevent_delete_default_dataset FROM public;
REVOKE EXECUTE ON FUNCTION timeseries.create_release FROM public;
REVOKE EXECUTE ON FUNCTION timeseries.update_release FROM public;
REVOKE EXECUTE ON FUNCTION timeseries.cancel_release FROM public;
REVOKE EXECUTE ON FUNCTION timeseries.list_releases FROM public;
REVOKE EXECUTE ON FUNCTION timeseries.list_access_levels FROM public;
REVOKE EXECUTE ON FUNCTION timeseries.access_levels_insert FROM public;
REVOKE EXECUTE ON FUNCTION timeseries.set_access_level_default FROM public;
REVOKE EXECUTE ON FUNCTION timeseries.access_levels_delete FROM public;
REVOKE EXECUTE ON FUNCTION timeseries.dataset_update FROM public;
REVOKE EXECUTE ON FUNCTION timeseries.read_ts_history_raw FROM public;

GRANT EXECUTE ON FUNCTION timeseries.insert_collect_from_tmp TO timeseries_reader;
GRANT EXECUTE ON FUNCTION timeseries.collection_remove TO timeseries_reader;
GRANT EXECUTE ON FUNCTION timeseries.collection_delete TO timeseries_reader;
GRANT EXECUTE ON FUNCTION timeseries.dataset_exists TO timeseries_reader;
GRANT EXECUTE ON FUNCTION timeseries.keys_in_dataset TO timeseries_reader;
GRANT EXECUTE ON FUNCTION timeseries.get_set_of_keys TO timeseries_reader;
GRANT EXECUTE ON FUNCTION timeseries.read_metadata_raw TO timeseries_reader;
GRANT EXECUTE ON FUNCTION timeseries.read_metadata_localized_raw TO timeseries_reader;
GRANT EXECUTE ON FUNCTION timeseries.read_ts_raw(TEXT[], DATE, BOOLEAN) TO timeseries_reader;
GRANT EXECUTE ON FUNCTION timeseries.read_ts_raw(DATE, BOOLEAN) TO timeseries_reader;
GRANT EXECUTE ON FUNCTION timeseries.read_ts_dataset_raw(TEXT[], DATE, BOOLEAN) TO timeseries_reader;
GRANT EXECUTE ON FUNCTION timeseries.read_ts_dataset_raw(DATE, BOOLEAN) TO timeseries_reader;
GRANT EXECUTE ON FUNCTION timeseries.get_latest_vintages_metadata TO timeseries_reader;
GRANT EXECUTE ON FUNCTION timeseries.get_latest_vintages_metadata_localized TO timeseries_reader;
GRANT EXECUTE ON FUNCTION timeseries.fill_read_tmp_regex TO timeseries_reader;
GRANT EXECUTE ON FUNCTION timeseries.list_datasets TO timeseries_reader;
GRANT EXECUTE ON FUNCTION timeseries.list_releases TO timeseries_reader;
GRANT EXECUTE ON FUNCTION timeseries.list_access_levels TO timeseries_reader;
GRANT EXECUTE ON FUNCTION timeseries.read_ts_history_raw TO timeseries_reader;

GRANT EXECUTE ON FUNCTION timeseries.assign_dataset TO timeseries_writer;
GRANT EXECUTE ON FUNCTION timeseries.md_unlocal_upsert TO timeseries_writer;
GRANT EXECUTE ON FUNCTION timeseries.md_local_upsert TO timeseries_writer;
GRANT EXECUTE ON FUNCTION timeseries.build_meta_status TO timeseries_writer;
GRANT EXECUTE ON FUNCTION timeseries.insert_from_tmp TO timeseries_writer;
GRANT EXECUTE ON FUNCTION timeseries.change_access_level TO timeseries_writer;
GRANT EXECUTE ON FUNCTION timeseries.change_access_level_dataset TO timeseries_writer;


GRANT EXECUTE ON FUNCTION timeseries.insert_collect_from_tmp TO timeseries_admin;
GRANT EXECUTE ON FUNCTION timeseries.collection_remove TO timeseries_admin;
GRANT EXECUTE ON FUNCTION timeseries.collection_delete TO timeseries_admin;
GRANT EXECUTE ON FUNCTION timeseries.dataset_exists TO timeseries_admin;
GRANT EXECUTE ON FUNCTION timeseries.keys_in_dataset TO timeseries_admin;
GRANT EXECUTE ON FUNCTION timeseries.get_set_of_keys TO timeseries_admin;
GRANT EXECUTE ON FUNCTION timeseries.read_metadata_raw TO timeseries_admin;
GRANT EXECUTE ON FUNCTION timeseries.read_metadata_localized_raw TO timeseries_admin;
GRANT EXECUTE ON FUNCTION timeseries.read_ts_raw(TEXT[], DATE, BOOLEAN) TO timeseries_admin;
GRANT EXECUTE ON FUNCTION timeseries.read_ts_raw(DATE, BOOLEAN) TO timeseries_admin;
GRANT EXECUTE ON FUNCTION timeseries.read_ts_dataset_raw(TEXT[], DATE, BOOLEAN) TO timeseries_admin;
GRANT EXECUTE ON FUNCTION timeseries.read_ts_dataset_raw(DATE, BOOLEAN) TO timeseries_admin;
GRANT EXECUTE ON FUNCTION timeseries.get_latest_vintages_metadata TO timeseries_admin;
GRANT EXECUTE ON FUNCTION timeseries.get_latest_vintages_metadata_localized TO timeseries_admin;
GRANT EXECUTE ON FUNCTION timeseries.fill_read_tmp_regex TO timeseries_admin;
GRANT EXECUTE ON FUNCTION timeseries.create_dataset TO timeseries_admin;
GRANT EXECUTE ON FUNCTION timeseries.assign_dataset TO timeseries_admin;
GRANT EXECUTE ON FUNCTION timeseries.md_unlocal_upsert TO timeseries_admin;
GRANT EXECUTE ON FUNCTION timeseries.md_local_upsert TO timeseries_admin;
GRANT EXECUTE ON FUNCTION timeseries.build_meta_status TO timeseries_admin;
GRANT EXECUTE ON FUNCTION timeseries.insert_from_tmp TO timeseries_admin;
GRANT EXECUTE ON FUNCTION timeseries.list_datasets TO timeseries_admin;
GRANT EXECUTE ON FUNCTION timeseries.change_access_level TO timeseries_admin;
GRANT EXECUTE ON FUNCTION timeseries.change_access_level_dataset TO timeseries_admin;
GRANT EXECUTE ON FUNCTION timeseries.dataset_delete TO timeseries_admin;
GRANT EXECUTE ON FUNCTION timeseries.delete_ts TO timeseries_admin;
GRANT EXECUTE ON FUNCTION timeseries.delete_ts_edge TO timeseries_admin;
GRANT EXECUTE ON FUNCTION timeseries.delete_ts_old_vintages TO timeseries_admin;
GRANT EXECUTE ON FUNCTION timeseries.dataset_trim TO timeseries_admin;
GRANT EXECUTE ON FUNCTION timeseries.prevent_delete_default_dataset TO timeseries_admin;
GRANT EXECUTE ON FUNCTION timeseries.create_release TO timeseries_admin;
GRANT EXECUTE ON FUNCTION timeseries.update_release TO timeseries_admin;
GRANT EXECUTE ON FUNCTION timeseries.cancel_release TO timeseries_admin;
GRANT EXECUTE ON FUNCTION timeseries.list_releases TO timeseries_admin;
GRANT EXECUTE ON FUNCTION timeseries.list_access_levels TO timeseries_admin;
GRANT EXECUTE ON FUNCTION timeseries.access_levels_insert TO timeseries_admin;
GRANT EXECUTE ON FUNCTION timeseries.set_access_level_default TO timeseries_admin;
GRANT EXECUTE ON FUNCTION timeseries.access_levels_delete TO timeseries_admin;
GRANT EXECUTE ON FUNCTION timeseries.dataset_update TO timeseries_admin;
GRANT EXECUTE ON FUNCTION timeseries.read_ts_history_raw TO timeseries_admin;
