serveDublinCore <- function(id,lang = 'de',
                            lookup_env = "meta_data_localized",
                            con = NULL){
  
  if(exists(id,envir = get(lookup_env))){
    mi <- get(id,envir = get(lookup_env))[[lang]]
  }
  
  
  dc_elements_list <- list(
    contributor = NULL,
    coverage  = paste(mi$coverage_temp,
                      mi$coverage_spatial,
                      sep = ';'), 
    creator = NULL, # generated by
    date = NULL, # generated on
    description = mi$description, 
    format = NULL,
    identifier = id,
    language = lang,
    publisher = NULL,
    relation = NULL,
    rights = NULL,
    source = mi$source,
    subject = mi$keywords,
    title = mi$title,
    type = NULL)
  
  dc_elements_list
  
  
}





