#' Update Meta Information Records
#' 
#' When a time series is stored to the database by \code{\link{storeTimeSeries}} 
#' a minimal unlocalized (i.e. untranslatable) meta information record is being 
#' generated. This meta information can be supplement using the updateMetaInformation
#' methods. Depending on the class of the environment that holds the
#' meta information localized or unlocalized meta information is updated. 
#' NOTE: AVOID looping over this function. This functions accepts entire environments
#' and creates large SQL queries instead of looping over multiple small queries. 
#' In other words loops are moved to the databse level for massive speed gain. 
#' 
#' @param meta_envir object of class meta_env. Most likely
#' generated by \code{\link{addMetaInformation}}
#' @param con a PostgreSQL connection object
#' @param schema character name of the schema to write to. Defaults to 'timeseries'.
#' @param tbl character name of the meta information table to write to. 
#' Defaults to 'meta_data_unlocalized'.
#' @param keys character vector of time series. If specified only the selected 
#' meta information is stored. Defaults to NULL which stores all meta information
#' records in the environment. 
#' @export
updateMetaInformation <- function(meta_envir,con,
                          schema = "timeseries",
                          tbl = "meta_data_unlocalized",
                          keys=NULL) {
  UseMethod("updateMetaInformation")
} 


#' @rdname updateMetaInformation
#' @export
updateMetaInformation.meta_env <- function(meta_envir,con,
                                           schema = "timeseries",
                                           tbl = "meta_data_unlocalized",
                                           keys=NULL){
  
  l <- as.list(meta_envir)
  
  # specification of keys can be used
  # to only store selected parts of the
  # meta infomration environment
  if(!is.null(keys)){
    l <- l[keys]  
  }
 
  # Minimal sanitizer to avoid trouble
  # when meta information gets too crazy... maybe need to escape things.
  # Did you really name your son Robert); DROP table students?
  l <- lapply(l,function(x){
    san <- lapply(x,gsub,pattern="'|DROP|DELETE|UPDATE|SELECT",
                  replacement="",ignore.case = T)
    class(san) <- c('miro','list')
    san
  })
  
  
  hstores <- lapply(l,createHstore)
  
  tbl <- paste(schema,tbl,sep=".")
  
  series <- names(l)
  md_values <- paste(paste0("('",
                            paste(series,
                                  hstores,
                                  sep="','"),
                            "')"),
                     collapse = ",")
  
  query_meta_data <- sprintf("BEGIN;
                             CREATE TEMPORARY TABLE 
                             md_updates(ts_key varchar, meta_data hstore) ON COMMIT DROP;
                             
                             INSERT INTO md_updates(ts_key, meta_data) VALUES %s;
                             LOCK TABLE %s.meta_data_unlocalized IN EXCLUSIVE MODE;
                             
                             UPDATE %s.meta_data_unlocalized
                             SET meta_data = md_updates.meta_data
                             FROM md_updates
                             WHERE md_updates.ts_key = %s.meta_data_unlocalized.ts_key;
                             COMMIT;", md_values, schema, schema, schema, schema)
  
  md_ok <- DBI::dbGetQuery(con,query_meta_data)
  if(is.null(md_ok)) cat("Meta information updated.")
}
